name: Linter
on: [push, pull_request]

jobs:
  php_cs_fixer:
    name: php_cs_fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Install Dependencies
        run: composer install --no-progress
      - name: Run PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff 1>&2